import type { TableProps } from "antd";
import { useState } from "react";
import { useTradingCalendar } from "../../presentation/coreModels";
import SectionPage from "../shared/SectionPage";

interface CalendarRow { key: string; tradeDate: string; exchange: string; calendarStatus: string; source: string; coverage: string; }
export default function CalendarRulesPage() {
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(50); const state = useTradingCalendar(page, pageSize); const total = state.data?.total;
  const known = (state.kind === "live" || state.kind === "empty") && typeof total === "number";
  const rows: CalendarRow[] = (state.data?.items ?? []).map((item, index) => ({ key: `${item.trading_date ?? index}-${item.exchange ?? index}`, tradeDate: item.trading_date ?? "未记录", exchange: item.exchange ?? "未记录", calendarStatus: item.status ?? "未记录", source: item.source ?? "未记录", coverage: item.is_trading_day ? "交易日" : "非交易日" }));
  const columns: TableProps<CalendarRow>["columns"] = [{ title: "日期", dataIndex: "tradeDate", width: 170 }, { title: "交易所", dataIndex: "exchange", width: 140 }, { title: "日历状态", dataIndex: "calendarStatus", width: 180 }, { title: "来源", dataIndex: "source", width: 240 }, { title: "交易日", dataIndex: "coverage", width: 150 }];
  return <SectionPage title="认证交易日历" subtitle="交易日历来源、覆盖范围与确认状态" relatedId="rules:calendar" provenance={{ ...state.provenance, sourceVersion: state.data?.source_version ?? state.provenance.sourceVersion }} metadataStatusText="只读认证日历 · 服务端分页 · 无 weekday fallback" statusLabel={known ? "已接入（只读）" : state.message} statusTone={known ? "info" : "review"} metrics={[{ label: "日历记录", value: known ? total : "状态未知", detail: "当前服务端筛选范围", tone: known ? "info" : "review" }, { label: "已确认", value: known ? state.data?.summary?.confirmed ?? "未记录" : "状态未知", detail: "只使用已记录状态", tone: "info" }, { label: "未解决", value: known ? state.data?.summary?.unresolved ?? "未记录" : "状态未知", detail: "保持 fail closed", tone: "review" }, { label: "weekday fallback", value: "禁止", detail: "不从周几猜测交易日", tone: "reject" }]} tableTitle="日历覆盖与状态（服务端分页）" columns={columns} tableData={rows} tablePagination={known ? { current: state.data?.page ?? page, pageSize: state.data?.page_size ?? pageSize, total, onChange: (nextPage, nextPageSize) => { setPage(nextPageSize === pageSize ? nextPage : 1); setPageSize(nextPageSize); } } : undefined} tableSearchEnabled={false} rowKey="key" emptyDescription={state.message} auditTitle="日历门禁" auditItems={[{ label: "日历缺失", value: "失败关闭", detail: "不使用 weekday 推断", tone: "reject" }, { label: "只读查询", value: "无写入", detail: "不触发日历同步或认证", tone: "info" }]} note="本页不授予回测、Research Readiness 或交易权限。" />;
}
