import type { TableProps } from "antd";
import { useState } from "react";
import { useFeeRules } from "../../presentation/coreModels";
import SectionPage from "../shared/SectionPage";

interface FeeRuleRow { key: string; feeType: string; feeValue: string; direction: string; exchange: string; effectiveFrom: string; effectiveTo: string; ruleVersion: string; source: string; }

export default function FeeRulesPage() {
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(50); const state = useFeeRules(page, pageSize); const total = state.data?.total;
  const known = (state.kind === "live" || state.kind === "empty") && typeof total === "number";
  const rows: FeeRuleRow[] = (state.data?.items ?? []).map((item, index) => ({ key: item.rule_version ?? String(index), feeType: item.rule_type ?? "未记录", feeValue: String(item.value ?? "未记录"), direction: item.direction ?? "未记录", exchange: item.exchange ?? "未记录", effectiveFrom: item.effective_from ?? "未记录", effectiveTo: item.effective_to ?? "持续有效", ruleVersion: item.rule_version ?? "未记录", source: item.source_name ?? "未记录" }));
  const columns: TableProps<FeeRuleRow>["columns"] = [{ title: "费用类型", dataIndex: "feeType", width: 190 }, { title: "登记值", dataIndex: "feeValue", width: 130 }, { title: "方向", dataIndex: "direction", width: 100 }, { title: "交易所", dataIndex: "exchange", width: 100 }, { title: "生效日期", dataIndex: "effectiveFrom", width: 140 }, { title: "失效日期", dataIndex: "effectiveTo", width: 140 }, { title: "规则版本", dataIndex: "ruleVersion", width: 190 }, { title: "官方依据", dataIndex: "source", width: 260 }];
  return <SectionPage title="费用规则" subtitle="已登记费用规则的生效期、版本、方向和官方依据" relatedId="rules:fees" provenance={{ ...state.provenance, sourceVersion: state.data?.registry_version ?? state.provenance.sourceVersion }} metadataStatusText="只读费用登记 · 服务端分页 · Source Hash 未记录" statusLabel={known ? "已接入（只读）" : state.message} statusTone={known ? "info" : "review"} metrics={[{ label: "费用记录", value: known ? total : "状态未知", detail: "当前服务端筛选范围", tone: known ? "info" : "review" }, { label: "卖出印花税", value: "卖出方向", detail: "按登记规则返回", tone: "info" }, { label: "滑点模型", value: "未纳入", detail: "没有官方费用规则登记", tone: "review" }, { label: "交易授权", value: "未授予", detail: "只读展示不创建订单", tone: "reject" }]} tableTitle="费用版本清单（服务端分页）" columns={columns} tableData={rows} tablePagination={known ? { current: state.data?.page ?? page, pageSize: state.data?.page_size ?? pageSize, total, onChange: (nextPage, nextPageSize) => { setPage(nextPageSize === pageSize ? nextPage : 1); setPageSize(nextPageSize); } } : undefined} tableSearchEnabled={false} rowKey="key" emptyDescription={state.message} auditTitle="会计一致性" auditItems={[{ label: "买卖区分", value: "已展示", detail: "印花税只标记为卖出方向", tone: "info" }, { label: "Source Hash", value: "未记录", detail: "不伪造官方源文件哈希", tone: "review" }, { label: "隐含费率", value: "禁止", detail: "未登记参数不作为官方费用规则展示", tone: "reject" }]} note="本页仅展示版本化会计依据，不对策略收益、交易成本或盈利能力作结论。" />;
}
