import type { TableProps } from "antd";
import { useState } from "react";
import { useTradingRules } from "../../presentation/coreModels";
import SectionPage from "../shared/SectionPage";

interface TradingRuleRow { key: string; ruleType: string; ruleValue: string; exchange: string; scope: string; effectiveFrom: string; effectiveTo: string; ruleVersion: string; source: string; }

export default function TradingRulesPage() {
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(50); const state = useTradingRules(page, pageSize); const total = state.data?.total;
  const known = (state.kind === "live" || state.kind === "empty") && typeof total === "number";
  const rows: TradingRuleRow[] = (state.data?.items ?? []).map((item, index) => ({ key: item.rule_version ?? String(index), ruleType: item.rule_type ?? "未记录", ruleValue: String(item.value ?? "未记录"), exchange: item.exchange ?? "未记录", scope: `${item.board ?? "未记录"}/${item.security_status ?? "未记录"}`, effectiveFrom: item.effective_from ?? "未记录", effectiveTo: item.effective_to ?? "持续有效", ruleVersion: item.rule_version ?? "未记录", source: item.source_name ?? "未记录" }));
  const columns: TableProps<TradingRuleRow>["columns"] = [{ title: "规则类型", dataIndex: "ruleType", width: 190 }, { title: "规则值", dataIndex: "ruleValue", width: 150 }, { title: "交易所", dataIndex: "exchange", width: 100 }, { title: "板块/状态", dataIndex: "scope", width: 150 }, { title: "生效日期", dataIndex: "effectiveFrom", width: 140 }, { title: "失效日期", dataIndex: "effectiveTo", width: 140 }, { title: "规则版本", dataIndex: "ruleVersion", width: 190 }, { title: "官方依据", dataIndex: "source", width: 260 }];
  return <SectionPage title="交易规则" subtitle="现有 A 股交易规则登记的生效期、版本和官方依据" relatedId="rules:trading" provenance={{ ...state.provenance, sourceVersion: state.data?.registry_version ?? state.provenance.sourceVersion }} metadataStatusText="只读规则登记 · 服务端分页 · Source Hash 未记录" statusLabel={known ? "已接入（只读）" : state.message} statusTone={known ? "info" : "review"} metrics={[{ label: "规则记录", value: known ? total : "状态未知", detail: "当前服务端筛选范围", tone: known ? "info" : "review" }, { label: "登记版本", value: state.data?.registry_version ?? "未记录", detail: "规则注册表版本", tone: "info" }, { label: "Source Hash", value: "未记录", detail: "不伪造官方源文件哈希", tone: "review" }, { label: "交易授权", value: "未授予", detail: "规则展示不创建订单", tone: "reject" }]} tableTitle="市场规则版本（服务端分页）" columns={columns} tableData={rows} tablePagination={known ? { current: state.data?.page ?? page, pageSize: state.data?.page_size ?? pageSize, total, onChange: (nextPage, nextPageSize) => { setPage(nextPageSize === pageSize ? nextPage : 1); setPageSize(nextPageSize); } } : undefined} tableSearchEnabled={false} rowKey="key" emptyDescription={state.message} auditTitle="规则安全" auditItems={[{ label: "官方依据", value: "已展示", detail: "来源参考以接口原始字段保留", tone: "info" }, { label: "未知规则", value: "失败关闭", detail: "不能猜测为主板 10%", tone: "reject" }, { label: "滑点模型", value: "未展示为官方规则", detail: "滑点不属于规则登记记录", tone: "review" }]} note="本页仅为规则审计视图，不授予回测、Research Readiness 或交易执行权限。" />;
}
