import type { TableProps } from "antd";
import { useState } from "react";
import { type DeepAnalysisListData, useDeepAnalysis } from "../../presentation/coreModels";
import { formatChinaDateTime } from "../../presentation/time";
import SectionPage from "../shared/SectionPage";

interface AnalysisRow { key: string; dimension: string; source: string; cutoff: string; quality: string; conclusion: string; }

export default function ResearchDeepPage() {
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(50); const state = useDeepAnalysis(page, pageSize); const analysis = state.data; const total = analysis?.total;
  const known = (state.kind === "live" || state.kind === "empty") && typeof total === "number";
  const rows: AnalysisRow[] = (analysis?.items ?? []).map((item: NonNullable<DeepAnalysisListData["items"]>[number], index) => ({ key: item.evidence_id ?? String(index), dimension: item.evidence_type ?? "维度未记录", source: [item.provider, item.source].filter(Boolean).join(" · ") || "来源未记录", cutoff: formatChinaDateTime(item.available_at ?? undefined), quality: `${item.quality_status ?? "质量未记录"} · ${item.usage_status ?? "用途状态未记录"}`, conclusion: `不生成结论 · 批次 ${item.batch_status ?? "未记录"}` }));
  const columns: TableProps<AnalysisRow>["columns"] = [{ title: "研究维度", dataIndex: "dimension", width: 180 }, { title: "证据来源", dataIndex: "source", width: 250 }, { title: "数据截止", dataIndex: "cutoff", width: 200 }, { title: "质量状态", dataIndex: "quality", width: 150 }, { title: "展示结论", dataIndex: "conclusion", width: 300 }];
  return <SectionPage title="深度分析" subtitle="已观察财报、公告与新闻证据的可得时间、来源和质量展示" relatedId="research:deep-analysis" provenance={{ ...state.provenance, sourceVersion: analysis?.source_version ?? state.provenance.sourceVersion }} metadataStatusText="只读证据聚合 · 服务端支持证券与证据类型筛选 · 不生成分析结论" statusLabel={known ? "已接入（只读）" : state.message} statusTone={known ? "info" : "review"} metrics={[{ label: "证据记录", value: known ? total : "状态未知", detail: "当前服务端筛选范围", tone: known ? "info" : "review" }, { label: "已观察", value: known ? analysis?.summary?.observed ?? 0 : "状态未知", detail: "保留质量状态与原始来源", tone: "info" }, { label: "已拒绝", value: known ? analysis?.summary?.rejected ?? 0 : "状态未知", detail: "拒绝记录不作为研究依据", tone: "review" }, { label: "分析结论", value: "不生成", detail: "证据聚合不构成 Alpha、候选或交易授权", tone: "reject" }]} tableTitle="研究证据维度（服务端分页）" columns={columns} tableData={rows} tablePagination={known ? { current: analysis?.page ?? page, pageSize: analysis?.page_size ?? pageSize, total, onChange: (nextPage, nextPageSize) => { setPage(nextPageSize === pageSize ? nextPage : 1); setPageSize(nextPageSize); } } : undefined} tableSearchEnabled={false} rowKey="key" emptyDescription={state.message} auditTitle="分析边界" auditItems={[{ label: "可得时间", value: "已展示", detail: "仅以 available_at 作为证据可得时点", tone: "info" }, { label: "未覆盖维度", value: "未记录", detail: "技术、情绪、行业与流动性无来源时不补造", tone: "review" }, { label: "未来函数", value: "禁止", detail: "不以发布时间或当前状态替代 available_at", tone: "reject" }, { label: "交易结论", value: "禁止", detail: "页面不创建订单或改变执行门禁", tone: "reject" }]} note="本页只展示已记录证据及其来源、时间和质量；它不把来源用途状态、记录存在或质量观察推断为 Research Readiness、候选发布、回测依据或交易权限。" />;
}
