import type { TableProps } from "antd";
import { useState } from "react";
import { type ResearchExclusionListData, useResearchExclusions } from "../../presentation/coreModels";
import { formatChinaDateTime } from "../../presentation/time";
import SectionPage from "../shared/SectionPage";

interface ExcludedRow { key: string; stockCode: string; reason: string; gate: string; evidence: string; reviewStatus: string; }

export default function ResearchExcludedPage() {
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(50); const state = useResearchExclusions(page, pageSize); const exclusions = state.data; const total = exclusions?.total;
  const known = (state.kind === "live" || state.kind === "empty") && typeof total === "number";
  const rows: ExcludedRow[] = (exclusions?.items ?? []).map((item: NonNullable<ResearchExclusionListData["items"]>[number], index) => ({ key: item.review_id ?? String(index), stockCode: item.stock_code ?? "股票代码未记录", reason: item.review_reason ?? "审核原因未记录", gate: `${item.readiness_status ?? "审核状态未记录"} · ${item.research_use_scope ?? "用途未记录"}`, evidence: `${item.requirement_profile ?? "规则档案未记录"} · 未解决 ${item.unresolved_fields?.join(", ") || "无"} · 拒绝 ${item.rejected_fields?.join(", ") || "无"}`, reviewStatus: `${item.provider_validation_status ?? "供应商校验未记录"} · ${formatChinaDateTime(item.reviewed_at ?? undefined)}` }));
  const columns: TableProps<ExcludedRow>["columns"] = [{ title: "股票代码", dataIndex: "stockCode", width: 150 }, { title: "排除原因", dataIndex: "reason", width: 300 }, { title: "阻断门禁", dataIndex: "gate", width: 190 }, { title: "证据", dataIndex: "evidence", width: 260 }, { title: "复核状态", dataIndex: "reviewStatus", width: 150 }];
  return <SectionPage title="排除与阻断" subtitle="资格审核中 review_required、rejected 的字段级事实展示" relatedId="research:excluded" provenance={{ ...state.provenance, sourceVersion: exclusions?.source_version ?? state.provenance.sourceVersion }} metadataStatusText="只读资格审核 · 服务端支持证券、状态与研究用途筛选 · 风险事件不纳入本接口" statusLabel={known ? "已接入（只读）" : state.message} statusTone={known ? "info" : "review"} metrics={[{ label: "排除记录", value: known ? total : "状态未知", detail: "当前服务端筛选范围", tone: known ? "info" : "review" }, { label: "待复核", value: known ? exclusions?.summary?.review_required ?? 0 : "状态未知", detail: "资格审核未完成", tone: "review" }, { label: "已拒绝", value: known ? exclusions?.summary?.rejected ?? 0 : "状态未知", detail: "保留拒绝字段与审核原因", tone: "reject" }, { label: "人工覆盖", value: "禁止", detail: "页面不提供强制放行或交易入口", tone: "reject" }]} tableTitle="排除明细（服务端分页）" columns={columns} tableData={rows} tablePagination={known ? { current: exclusions?.page ?? page, pageSize: exclusions?.page_size ?? pageSize, total, onChange: (nextPage, nextPageSize) => { setPage(nextPageSize === pageSize ? nextPage : 1); setPageSize(nextPageSize); } } : undefined} tableSearchEnabled={false} rowKey="key" emptyDescription={state.message} auditTitle="排除边界" auditItems={[{ label: "资格审核", value: "字段级展示", detail: "仅展示未解决字段、拒绝字段及审核原因", tone: "info" }, { label: "风险事件", value: "不纳入", detail: "风险事件不与资格审核事实混用", tone: "review" }, { label: "未知与缺失", value: "待复核", detail: "无法证明即保持 fail closed", tone: "review" }, { label: "交易结论", value: "禁止", detail: "页面不创建订单或改变执行门禁", tone: "reject" }]} note="本页只读展示资格审核记录；它不把审核排除推断为风险事件、持仓处置、候选结论或交易权限，也不提供人工强制放行。" />;
}
