import type { TableProps } from "antd";
import { useState } from "react";
import { type ResearchHoldingReviewListData, useResearchHoldingsReview } from "../../presentation/coreModels";
import { formatChinaDateTime } from "../../presentation/time";
import SectionPage from "../shared/SectionPage";

interface HoldingReviewRow { key: string; stockCode: string; positionState: string; researchState: string; riskState: string; actionBoundary: string; }

export default function ResearchHoldingsPage() {
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(50); const state = useResearchHoldingsReview(page, pageSize); const holdings = state.data; const total = holdings?.total;
  const known = (state.kind === "live" || state.kind === "empty") && typeof total === "number";
  const rows: HoldingReviewRow[] = (holdings?.items ?? []).map((item: NonNullable<ResearchHoldingReviewListData["items"]>[number], index) => ({ key: item.stock_code ?? String(index), stockCode: item.stock_code ?? "股票代码未记录", positionState: `总量 ${item.total_qty ?? "未记录"} · 可用 ${item.available_qty ?? "未记录"} · 冻结 ${item.frozen_qty ?? "未记录"}`, researchState: `${item.readiness_status ?? "审核未记录"} · ${item.research_use_scope ?? "用途未记录"} · ${item.requirement_profile ?? "规则档案未记录"}`, riskState: `${item.risk_association_status ?? "未记录"} · 风险事件无证券关联`, actionBoundary: `不生成动作 · ${item.review_reason ?? "审核原因未记录"} · 持仓时间 ${formatChinaDateTime(item.position_updated_at ?? undefined)}` }));
  const columns: TableProps<HoldingReviewRow>["columns"] = [{ title: "股票代码", dataIndex: "stockCode", width: 160 }, { title: "持仓状态", dataIndex: "positionState", width: 180 }, { title: "研究状态", dataIndex: "researchState", width: 190 }, { title: "风险状态", dataIndex: "riskState", width: 180 }, { title: "动作边界", dataIndex: "actionBoundary", width: 300 }];
  return <SectionPage title="持仓再评估" subtitle="持仓数量与最新资格审核的只读关联展示" relatedId="research:holdings" provenance={{ ...state.provenance, sourceVersion: holdings?.source_version ?? state.provenance.sourceVersion }} metadataStatusText="只读持仓与资格审核 · 风险事件无证券关联时保持未记录 · 不生成交易动作" statusLabel={known ? "已接入（只读）" : state.message} statusTone={known ? "info" : "review"} metrics={[{ label: "在持标的", value: known ? total : "状态未知", detail: "当前 simulation 持仓范围", tone: known ? "info" : "review" }, { label: "审核已记录", value: known ? holdings?.summary?.readiness_recorded ?? 0 : "状态未知", detail: "仅关联每标的最新审核", tone: "info" }, { label: "审核未记录", value: known ? holdings?.summary?.readiness_not_recorded ?? 0 : "状态未知", detail: "缺失不推断为已通过", tone: "review" }, { label: "强制换股", value: "禁止", detail: "页面不生成持仓处置或订单", tone: "reject" }]} tableTitle="持仓研究复核（服务端分页）" columns={columns} tableData={rows} tablePagination={known ? { current: holdings?.page ?? page, pageSize: holdings?.page_size ?? pageSize, total, onChange: (nextPage, nextPageSize) => { setPage(nextPageSize === pageSize ? nextPage : 1); setPageSize(nextPageSize); } } : undefined} tableSearchEnabled={false} rowKey="key" emptyDescription={state.message} auditTitle="操作边界" auditItems={[{ label: "资格审核", value: "只读关联", detail: "最新审核记录不等于交易授权", tone: "info" }, { label: "风险事件", value: "未记录", detail: "风险事件表没有证券关联，不推断持仓风险状态", tone: "review" }, { label: "加仓与卖出", value: "需授权", detail: "仍经 Risk 与 Execution Gate，且遵守 T+1 可用数量", tone: "review" }, { label: "AI 下单", value: "禁止", detail: "AI 无订单创建权限", tone: "reject" }]} note="本页仅关联已记录持仓及最新资格审核；它不形成持有、减仓、加仓或换股建议，不把风险事件缺少证券关联推断为安全，并且不会自动执行任何订单。" />;
}
