import type { TableProps } from "antd";
import { useState } from "react";
import { type SystemAlertListData, type SystemHealthData, type SystemJobListData, useSystemAlerts, useSystemHealth, useSystemJobs } from "../../presentation/coreModels";
import { pendingState } from "../../presentation/readOnlyApi";
import { formatChinaDateTime } from "../../presentation/time";
import SectionPage from "../shared/SectionPage";

interface SystemRow { key: string; primary: string; eventTime: string; owner: string; version: string; relatedId: string; status: string; }

const systemColumns: TableProps<SystemRow>["columns"] = [
  { title: "事件/任务 ID", dataIndex: "primary", width: 230 }, { title: "时间", dataIndex: "eventTime", width: 210 }, { title: "责任组件", dataIndex: "owner", width: 190 }, { title: "版本", dataIndex: "version", width: 180 }, { title: "关联 ID", dataIndex: "relatedId", width: 230 }, { title: "状态", dataIndex: "status", width: 150 },
];

export function SchedulePage() {
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(50); const state = useSystemJobs(page, pageSize); const jobs = state.data; const total = jobs?.total;
  const known = (state.kind === "live" || state.kind === "empty") && typeof total === "number";
  const rows: SystemRow[] = (jobs?.items ?? []).map((item: NonNullable<SystemJobListData["items"]>[number], index) => ({ key: item.job_id ?? String(index), primary: item.job_type ?? "未记录", eventTime: formatChinaDateTime(item.updated_at ?? item.created_at), owner: item.last_stage ?? "audit.async_jobs", version: "operation-job-audit-v1", relatedId: item.operation_approval_id ?? item.job_id ?? "未记录", status: `${item.status ?? "未记录"} · ${item.progress ?? "未记录"}% · 重试 ${item.retry_count ?? 0}/${item.max_retries ?? "未记录"}` }));
  return <SectionPage title="任务时序" subtitle="已审计异步任务与调度登记状态的只读展示" relatedId="system:jobs" provenance={{ ...state.provenance, sourceVersion: jobs?.source_version ?? state.provenance.sourceVersion }} metadataStatusText="只读聚合 · 不启动、停止、重试或修改任务 · 调度运行态单独标明观测范围" statusLabel={known ? "已接入（只读）" : state.message} statusTone={known ? "info" : "review"} metrics={[{ label: "待处理任务", value: known ? jobs?.summary?.pending ?? 0 : "状态未知", detail: "queued、retry_wait 或 cancel_requested", tone: "review" }, { label: "运行中任务", value: known ? jobs?.summary?.running ?? 0 : "状态未知", detail: "仅 audit.async_jobs 的 running 记录", tone: "info" }, { label: "失败或阻断", value: known ? jobs?.summary?.failed_or_blocked ?? 0 : "状态未知", detail: "应在系统告警页独立查看", tone: "review" }, { label: "调度运行态", value: jobs?.scheduler?.runtime_status === "not_observed" ? "未观测" : "状态未知", detail: "未将静态调度声明推断为运行成功", tone: "review" }]} tableTitle="已审计任务（服务端分页）" columns={systemColumns} tableData={rows} tablePagination={known ? { current: jobs?.page ?? page, pageSize: jobs?.page_size ?? pageSize, total, onChange: (nextPage, nextPageSize) => { setPage(nextPageSize === pageSize ? nextPage : 1); setPageSize(nextPageSize); } } : undefined} tableSearchEnabled={false} rowKey="key" emptyDescription={state.message} auditTitle="调度安全" auditItems={[{ label: "任务时区", value: jobs?.scheduler?.timezone ?? "未记录", detail: "调度声明使用的时区；运行态未观测", tone: "info" }, { label: "调度登记", value: jobs?.scheduler?.registration_status === "not_observed" ? "未观测" : "状态未知", detail: jobs?.scheduler?.registration_source ?? "未记录", tone: "review" }, { label: "自动订单", value: "禁止", detail: "本页不创建订单，且不构成交易授权", tone: "reject" }, { label: "失败重试", value: "只读可追踪", detail: "展示任务的重试次数，不提供重试操作", tone: "review" }]} note="空列表仅表示当前页未返回审计任务；调度运行状态未观测不代表调度器不可用，更不代表研究、发布或交易已通过。" />;
}

export function SystemAlertsPage() {
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(50); const state = useSystemAlerts(page, pageSize); const alerts = state.data; const total = alerts?.total;
  const known = (state.kind === "live" || state.kind === "empty") && typeof total === "number";
  const categoryLabel = (value?: string) => ({ system_operation: "系统运行", data_qualification: "数据资格" }[value ?? ""] ?? "类别未记录");
  const rows: SystemRow[] = (alerts?.items ?? []).map((item: NonNullable<SystemAlertListData["items"]>[number], index) => ({ key: item.alert_id ?? String(index), primary: item.alert_type ?? "未记录", eventTime: formatChinaDateTime(item.event_time ?? undefined), owner: item.owner ?? "未记录", version: item.source_version ?? "未记录", relatedId: item.related_id ?? "未记录", status: `${categoryLabel(item.category)} · ${item.severity ?? "未记录"} · ${item.detail_code ?? "详情未记录"}` }));
  return <SectionPage title="系统告警" subtitle="系统运行、数据资格与业务发布状态的独立展示" relatedId="system:alerts" provenance={{ ...state.provenance, sourceVersion: alerts?.source_version ?? state.provenance.sourceVersion }} metadataStatusText="只读聚合 · 风险事件不纳入本接口 · 发布锁不在此页面变更" statusLabel={known ? "已接入（只读）" : state.message} statusTone={known ? "info" : "review"} metrics={[{ label: "系统运行记录", value: known ? alerts?.summary?.system_operation ?? 0 : "状态未知", detail: "仅 audit.async_jobs 中 failed/blocked 记录", tone: "review" }, { label: "数据资格阻断", value: known ? alerts?.summary?.data_qualification ?? 0 : "状态未知", detail: "仅既有数据阻断审核记录；不传播为 Readiness", tone: "review" }, { label: "业务发布", value: "未授予", detail: alerts?.business_release?.all_release_locks_closed ? "六把发布锁均关闭" : "存在开启的发布锁；仍不构成授权", tone: "reject" }, { label: "风险事件", value: "独立页面", detail: "本接口不读取 risk.risk_events", tone: "info" }]} tableTitle="系统告警记录（服务端分页）" columns={systemColumns} tableData={rows} tablePagination={known ? { current: alerts?.page ?? page, pageSize: alerts?.page_size ?? pageSize, total, onChange: (nextPage, nextPageSize) => { setPage(nextPageSize === pageSize ? nextPage : 1); setPageSize(nextPageSize); } } : undefined} tableSearchEnabled={false} rowKey="key" emptyDescription={state.message} auditTitle="告警职责" auditItems={[{ label: "系统运行", value: "独立", detail: "仅运行记录失败或阻断进入本页", tone: "info" }, { label: "数据资格", value: "独立", detail: "阻断记录不等于 Research Readiness 结论", tone: "info" }, { label: "发布锁", value: "只读", detail: "当前状态单独展示，不能由本页解除", tone: "reject" }, { label: "风险事件", value: "排除", detail: "风险命中继续在风险页面归档", tone: "info" }]} note="本页不以单一“正常”掩盖不同类别；空列表仅表示当前查询未返回记录，不表示基础设施、数据资格、发布或交易已通过。" />;
}

export function SystemHealthPage() {
  const state = useSystemHealth(); const health = state.data; const known = state.kind === "live" || state.kind === "empty";
  const statusLabel = (value?: string) => ({ observed: "已观察", partial_observed: "部分已观察", available: "可用", unavailable: "不可用", not_evaluated: "未评估", records_observed: "记录已观察", not_granted: "未授予" }[value ?? ""] ?? "状态未知");
  const rows: SystemRow[] = [
    ...(health?.infrastructure?.components ?? []).map((item, index) => ({ key: `infrastructure-${item.component ?? index}`, primary: item.component ?? "未记录", eventTime: item.observed_at ?? "未记录", owner: "基础设施", version: "未记录", relatedId: "system:health", status: `${statusLabel(item.status)} · ${item.detail ?? "详情未记录"}` })),
    { key: "data-qualification", primary: "数据资格", eventTime: health?.data_qualification?.summary?.latest_reviewed_at ?? "未记录", owner: "market.research_readiness_reviews", version: "field-readiness-v2", relatedId: "data:qualification", status: `${statusLabel(health?.data_qualification?.status)} · 总记录 ${health?.data_qualification?.summary?.total ?? "未记录"}` },
    { key: "business-release", primary: "业务发布", eventTime: "当前配置快照", owner: "execution safety settings", version: "execution-safety-v4", relatedId: "trade:execution-status", status: `${statusLabel(health?.business_release?.status)} · 发布锁 ${health?.business_release?.all_release_locks_closed ? "全部关闭" : "存在开启项"}` },
  ];
  return <SectionPage title="服务健康" subtitle="基础设施连通、数据资格和业务发布三种状态的分离展示" relatedId="system:health" provenance={{ ...state.provenance, sourceVersion: health?.source_version ?? state.provenance.sourceVersion }} metadataStatusText="只读聚合 · 不将基础设施可用推断为数据就绪或业务发布" statusLabel={known ? "已接入（只读）" : state.message} statusTone={known ? "info" : "review"} metrics={[{ label: "基础设施", value: statusLabel(health?.infrastructure?.status), detail: "仅展示本次请求可观察到的 API 与数据库", tone: health?.infrastructure?.status === "observed" ? "info" : "review" }, { label: "数据资格", value: statusLabel(health?.data_qualification?.status), detail: `Ready ${health?.data_qualification?.summary?.ready ?? "未记录"}；不传播为 Research Readiness`, tone: "review" }, { label: "业务发布", value: statusLabel(health?.business_release?.status), detail: "发布锁状态不构成交易授权", tone: "reject" }, { label: "订单创建", value: "禁止", detail: "健康接口只读，不能创建订单或变更发布锁", tone: "reject" }]} tableTitle="服务连通与资格记录" columns={systemColumns} tableData={rows} rowKey="key" emptyDescription={state.message} auditTitle="发布锁状态" auditItems={(health?.business_release?.release_locks ?? []).map((lock) => ({ label: lock.label, value: lock.enabled ? "开启" : "关闭", detail: lock.reason, tone: lock.enabled ? "review" as const : "reject" as const }))} note="接口不检查或臆测没有运行登记来源的 Worker、Redis 等组件；基础设施、数据资格和业务发布必须分别判断，且本页不授予研究、发布或交易权限。" />;
}

export function SystemAuditPage() {
  const state = pendingState("平台审计接口待接入", "system-audit-ui-v1");
  return <SectionPage title="平台审计" subtitle="平台级只读操作、配置版本、关联 ID 与完整性 Hash 审计" relatedId="system:audit" provenance={state.provenance} metrics={[{ label: "审计事件", value: "待接入", detail: "需有稳定 event_id", tone: "review" }, { label: "关联链路", value: "待接入", detail: "trace_id、run_id 与版本可追踪", tone: "review" }, { label: "配置变更", value: "待接入", detail: "变更需有审批和回滚", tone: "review" }, { label: "删除审计", value: "禁止", detail: "审计记录不可静默删除", tone: "reject" }]} tableTitle="平台审计事件" columns={systemColumns} rowKey="key" emptyDescription={state.message} auditTitle="审计边界" auditItems={[{ label: "风险事件", value: "独立", detail: "风险命中在风险模块归档", tone: "info" }, { label: "系统告警", value: "独立", detail: "服务失败在系统告警归档", tone: "info" }, { label: "完整性 Hash", value: "必须", detail: "审计数据需要可验证", tone: "info" }]} note="平台审计页用于关联和追踪系统行为，不提供修改安全开关、订单或业务数据的能力。" />;
}
