import type { TableProps } from "antd";
import { useState } from "react";
import { useSecurityStatus } from "../../presentation/coreModels";
import SectionPage from "../shared/SectionPage";

interface LimitRuleRow { key: string; stockCode: string; effectiveFrom: string; effectiveTo: string; securityStatus: string; evidence: string; evidenceVersion: string; resolution: string; }

export default function MarketLimitPage() {
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(50); const state = useSecurityStatus(page, pageSize); const total = state.data?.total;
  const known = (state.kind === "live" || state.kind === "empty") && typeof total === "number";
  const rows: LimitRuleRow[] = (state.data?.items ?? []).map((item, index) => ({ key: `${item.run_id ?? index}-${item.stock_code ?? index}-${item.effective_from ?? index}`, stockCode: item.stock_code ?? "未记录", effectiveFrom: item.effective_from ?? "未记录", effectiveTo: item.effective_to ?? "未记录", securityStatus: item.status ?? "未记录", evidence: item.evidence_source ?? "未记录", evidenceVersion: item.evidence_version ?? "未记录", resolution: item.resolution_status ?? "未记录" }));
  const columns: TableProps<LimitRuleRow>["columns"] = [{ title: "证券代码", dataIndex: "stockCode", width: 150 }, { title: "生效日期", dataIndex: "effectiveFrom", width: 150 }, { title: "失效日期", dataIndex: "effectiveTo", width: 150 }, { title: "证券状态", dataIndex: "securityStatus", width: 160 }, { title: "证据来源", dataIndex: "evidence", width: 280 }, { title: "证据版本", dataIndex: "evidenceVersion", width: 210 }, { title: "价格限制解析", dataIndex: "resolution", width: 170 }];
  return <SectionPage title="涨跌停与状态" subtitle="已审核证券状态及价格限制解析记录" relatedId="market:limit" provenance={{ ...state.provenance, sourceVersion: state.data?.source_version ?? state.provenance.sourceVersion }} metadataStatusText="只读状态审核 · 服务端分页 · 不按代码前缀推断规则" statusLabel={known ? "已接入（只读）" : state.message} statusTone={known ? "info" : "review"} metrics={[{ label: "状态记录", value: known ? total : "状态未知", detail: "当前服务端筛选范围", tone: known ? "info" : "review" }, { label: "unresolved", value: known ? state.data?.summary?.unresolved ?? "未记录" : "状态未知", detail: "保持 fail closed", tone: "review" }, { label: "价格限制解析", value: "未记录", detail: "状态审核不等于涨跌停规则解析", tone: "review" }, { label: "交易授权", value: "未授予", detail: "状态展示不创建订单", tone: "reject" }]} tableTitle="证券状态审核记录（服务端分页）" columns={columns} tableData={rows} tablePagination={known ? { current: state.data?.page ?? page, pageSize: state.data?.page_size ?? pageSize, total, onChange: (nextPage, nextPageSize) => { setPage(nextPageSize === pageSize ? nextPage : 1); setPageSize(nextPageSize); } } : undefined} tableSearchEnabled={false} rowKey="key" emptyDescription={state.message} auditTitle="微观规则边界" auditItems={[{ label: "代码前缀", value: "不推断", detail: "板块与价格限制需要独立证据", tone: "reject" }, { label: "价格限制", value: "未记录", detail: "不得从状态表生成规则结论", tone: "review" }, { label: "停牌", value: "保留审核事实", detail: "交易执行仍需独立 Gate 和授权", tone: "info" }]} note="本页只读展示证券状态审核；它不解析未记录的价格限制，也不授予回测、Research Readiness 或交易执行权限。" />;
}
