import type { TableProps } from "antd";
import { useState } from "react";
import { type MarketClassificationListData, useConceptBoards, useIndustryClassifications } from "../../presentation/coreModels";
import { formatChinaDateTime } from "../../presentation/time";
import SectionPage from "../shared/SectionPage";

interface SectorRow { key: string; sectorId: string; sectorName: string; classificationSource: string; effectiveRange: string; coverage: string; validation: string; }

export default function MarketSectorPage() {
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(50); const state = useIndustryClassifications(page, pageSize); const conceptState = useConceptBoards(page, pageSize); const classifications = state.data; const total = classifications?.total;
  const known = (state.kind === "live" || state.kind === "empty") && typeof total === "number";
  const rows: SectorRow[] = (classifications?.items ?? []).map((item: NonNullable<MarketClassificationListData["items"]>[number], index) => ({ key: item.classification_name ?? String(index), sectorId: item.classification_kind ?? "industry", sectorName: item.classification_name ?? "行业未记录", classificationSource: `${item.provider ?? "未记录"} · ${item.source ?? "未记录"}`, effectiveRange: "当前快照、非历史还原数据", coverage: `当前 ${item.stock_count ?? "未记录"} 只`, validation: `${item.quality_status ?? "未记录"} · PIT ${item.pit_capable ? "支持" : "不支持"}` }));
  const columns: TableProps<SectorRow>["columns"] = [
    { title: "板块 ID", dataIndex: "sectorId", width: 160 }, { title: "行业/板块", dataIndex: "sectorName", width: 200 }, { title: "分类来源", dataIndex: "classificationSource", width: 220 }, { title: "有效区间", dataIndex: "effectiveRange", width: 220 }, { title: "覆盖范围", dataIndex: "coverage", width: 160 }, { title: "验证状态", dataIndex: "validation", width: 170 },
  ];
  return <SectionPage title="行业与板块" subtitle="行业当前快照的来源、覆盖范围与非 PIT 使用边界" relatedId="market:sector" provenance={{ ...state.provenance, sourceVersion: classifications?.source_version ?? state.provenance.sourceVersion }} metadataStatusText="只读行业当前快照 · legacy_internal · unverified · 不支持 PIT" statusLabel={known ? "已接入（当前快照）" : state.message} statusTone="review" metrics={[{ label: "行业分类", value: known ? total : "状态未知", detail: "当前快照、非历史还原数据", tone: "review" }, { label: "概念板块", value: conceptState.data?.availability_status === "unavailable" ? "未接入" : "状态未知", detail: "正式数据源尚未接入，不使用行业字段替代", tone: "review" }, { label: "快照更新时间", value: known ? formatChinaDateTime(classifications?.summary?.latest_snapshot_updated_at ?? undefined) : "状态未知", detail: "不是 Provider 抓取时间", tone: "review" }, { label: "历史研究", value: "禁止", detail: "不进入回测、Walk Forward、训练或历史因子", tone: "reject" }]} tableTitle="行业当前快照（服务端分页）" columns={columns} tableData={rows} tablePagination={known ? { current: classifications?.page ?? page, pageSize: classifications?.page_size ?? pageSize, total, onChange: (nextPage, nextPageSize) => { setPage(nextPageSize === pageSize ? nextPage : 1); setPageSize(nextPageSize); } } : undefined} tableSearchEnabled={false} rowKey="key" emptyDescription={state.message} auditTitle="分类控制" auditItems={[{ label: "行业分类", value: "当前快照", detail: "不将 current_snapshot 声称为正式 Provider 或 PIT 事实", tone: "review" }, { label: "概念与交易所板块", value: "独立建模", detail: "不混用行业字段；概念板块正式数据源尚未接入", tone: "review" }, { label: "历史归属", value: "禁止回填", detail: "不能使用今天分类回写历史研究或回测", tone: "reject" }, { label: "集中度下单", value: "禁止", detail: "页面不改变 Risk Engine 或订单边界", tone: "reject" }]} note="本页只展示 fundamental.stocks 的未验证行业当前快照。概念板块正式来源尚未接入；provider、正式版本、抓取时间和有效期均未记录的字段不能作为历史研究、回测、训练、因子计算、选股、风险调整或交易执行依据。" />;
}
