import type { TableProps } from "antd";
import { useState } from "react";
import { type ObservedLiquidityListData, useObservedLiquidity } from "../../presentation/coreModels";
import { formatChinaDateTime } from "../../presentation/time";
import SectionPage from "../shared/SectionPage";

interface LiquidityRow { key: string; stockCode: string; period: string; volume: string; amount: string; source: string; validation: string; batchHash: string; }

export default function MarketVolumePage() {
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(50); const state = useObservedLiquidity(page, pageSize); const total = state.data?.total;
  const known = (state.kind === "live" || state.kind === "empty") && typeof total === "number";
  const rows: LiquidityRow[] = (state.data?.items ?? []).map((item: NonNullable<ObservedLiquidityListData["items"]>[number], index) => ({ key: `${item.stock_code ?? index}-${item.quote_time ?? index}`, stockCode: item.stock_code ?? "未记录", period: `${item.period ?? "未记录"} · ${formatChinaDateTime(item.quote_time)}`, volume: item.volume == null ? "未记录" : `${item.volume} · ${item.volume_unit ?? "单位未记录"}`, amount: item.amount == null ? "未记录" : `${item.amount} · ${item.amount_unit ?? "单位未记录"}`, source: [item.provider, item.source, item.fetch_endpoint].filter(Boolean).join(" · ") || "未记录", validation: `${item.volume_status ?? "未记录"} · amount: ${item.amount_status ?? "未记录"}`, batchHash: `${item.batch_id ?? "未记录"} · ${item.raw_hash ?? "未记录"}` }));
  const observedVolumeCount = rows.filter((item) => item.validation.startsWith("observed")).length;
  const columns: TableProps<LiquidityRow>["columns"] = [
    { title: "证券代码", dataIndex: "stockCode", width: 130 }, { title: "快照时点", dataIndex: "period", width: 240 }, { title: "成交量", dataIndex: "volume", width: 180 }, { title: "成交额", dataIndex: "amount", width: 190 }, { title: "来源", dataIndex: "source", width: 240 }, { title: "字段状态", dataIndex: "validation", width: 190 }, { title: "批次 / Hash", dataIndex: "batchHash", width: 320 },
  ];
  return <SectionPage title="成交量与流动性" subtitle="已观察成交量、成交额记录、单位语义与字段级适用性" relatedId="market:volume" provenance={{ ...state.provenance, sourceVersion: state.data?.source_version ?? state.provenance.sourceVersion }} metadataStatusText="只读观察 · 服务端分页 · 不据此给出流动性结论或交易授权" statusLabel={known ? "已接入（只读）" : state.message} statusTone={known ? "info" : "review"} metrics={[{ label: "已观察成交量", value: known ? total : "状态未知", detail: known ? `本页 ${observedVolumeCount} 条有成交量记录；单位按入库规范为 shares` : "接口不可用时不将其视为 0", tone: known ? "info" : "review" }, { label: "成交额记录", value: known ? rows.filter((item) => !item.amount.startsWith("未记录")).length : "状态未知", detail: "数值原样记录；跨来源单位未记录", tone: "review" }, { label: "Amount 研究因子", value: "未授予", detail: "amount 未通过独立字段验证，不得用于研究、排序或交易判断", tone: "reject" }, { label: "流动性结论", value: "未授予", detail: "本页只展示快照，不构造流动性结论", tone: "reject" }]} tableTitle="成交量与成交额审计（服务端分页）" columns={columns} tableData={rows} tablePagination={known ? { current: state.data?.page ?? page, pageSize: state.data?.page_size ?? pageSize, total, onChange: (nextPage, nextPageSize) => { setPage(nextPageSize === pageSize ? nextPage : 1); setPageSize(nextPageSize); } } : undefined} tableSearchEnabled={false} rowKey="key" emptyDescription={state.message} auditTitle="字段级边界" auditItems={[{ label: "成交量", value: "已观察", detail: "实时抓取路径按 volume_shares 归一为 shares；仅表示记录存在", tone: "info" }, { label: "成交额", value: "未验证", detail: "持久化层未记录跨来源单位与独立验证证据，不能显示为 CNY 或授权使用", tone: "reject" }, { label: "单位换算", value: "不追加", detail: "页面不做二次换算，避免把未知语义放大为结论", tone: "review" }]} note="成交量与成交额必须保留来源、时点和状态。本页不把已观察记录、字段质量通过或数值存在推断为 Research Readiness、排名依据、流动性结论或订单权限。" />;
}
